<ips:template parameters="$mission" />
<div class="ipsPageHeader ipsBox ipsResponsive_pull ipsPadding ipsSpacer_bottom ipsClearfix">
    <h1 class="ipsType_pageTitle">{lang="mission_title_name" sprintf="$mission->name"}</h1>
    <hr class="ipsHr">
    <div class="ipsPageHeader__meta ipsFlex ipsFlex-jc:between ipsFlex-ai:center ipsFlex-fw:wrap ipsGap:3">
        <div class="ipsFlex-flex:11">
            <div class="ipsPhotoPanel ipsPhotoPanel_mini ipsPhotoPanel_notPhone ipsClearfix">
                {template="userPhoto" group="global" app="core" params="$mission->author(), 'mini', $mission->warningRef()"}
                <div>
                    <p class="ipsType_reset ipsType_blendLinks">
						<span class="ipsType_normal">
							<strong>{lang="byline_itemprop" htmlsprintf="$mission->author()->link($mission->warningRef(), NULL, $mission->isAnonymous())"}</strong><br />
							<span class="ipsType_light">{lang="in"} <a href="{$mission->container()->url()}">{$mission->container()->_formattedTitle|raw}</a></span>
						</span>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="ipsBox ipsResponsive_pull ipsPadding ipsSpacer_bottom">
    <div class="ipsSpacer_bottom">
        <strong>{lang="mission_start"}:</strong> {datetime="$mission->start" norelative="true"}
    </div>
    <div class="ipsSpacer_bottom">
        <strong>{lang="mission_end"}:</strong> {datetime="$mission->end" norelative="true"}
    </div>
    <div>
        {$mission->content|raw}
    </div>
</div>
{{if ($mission->canDelete() or $mission->canEdit() or $mission->canComment())}}
<div class="ipsClearfix">
    <ul class="ipsToolList ipsToolList_horizontal ipsSpacer_both ipsResponsive_hidePhone">
        {{if $mission->canComment()}}
        <li>
            <a href="{$url = \IPS\Http\Url::internal('app=penh&module=operations&controller=afteractionreport&do=add&id=' . $mission->id)}" class="ipsButton ipsButton_primary ipsButton_medium ipsButton_fullWidth">
                {lang="aar_create"}
            </a>
        </li>
        {{endif}}
        <li>
            <a href="#elMissionActions_menu" id="elMissionActions" class="ipsButton ipsButton_link ipsButton_medium ipsButton_fullWidth" data-ipsMenu>{lang="moderator_actions"} <i class="fa fa-caret-down"></i></a>
            <ul id="elMissionActions_menu" class="ipsMenu ipsMenu_auto ipsHide ipsType_reset">
                {{if $mission->canEdit()}}
                <li class="ipsMenu_item"><a href="{$mission->url()->setQueryString('do', 'edit')}">{lang="mission_edit"}</a></li>
                {{endif}}
                {{if $mission->canDelete()}}
                <li class="ipsMenu_item"><a href="{$mission->url()->setQueryString('do', 'delete')}">{lang="mission_delete"}</a></li>
                {{endif}}
            </ul>
        </li>
    </ul>
</div>
{{endif}}
{{$aars = $mission->comments();}}
{{if \count($aars) > 0}}
<div class="ipsBox ipsResponsive_pull ipsPadding_horizontal">
    <h3 class="ipsPadding_top">{lang="mission_aars"}</h3>
    <ul class="ipsDataList ipsDataList_reducedSpacing">
        {{foreach $aars as $aar}}
        {$aar->html()|raw}
        {{endforeach}}
    </ul>
</div>
{{endif}}
