<ips:template parameters="$operations=[]" />
<div class="ipsPageHeader ipsBox ipsResponsive_pull ipsPadding ipsSpacer_bottom ipsClearfix">
    <header>
        <h1 class="ipsType_pageTitle">{lang="operations_title"}</h1>
        <div class="ipsType_richText ipsType_normal">{lang="operations_subtitle"}</div>
    </header>
</div>
{{foreach $operations as $operation}}
    {template="operationRow" app="penh" group="operations" params="$operation"}
{{endforeach}}
