<ips:template parameters="$operation" />
<div class="ipsBox ipsResponsive_pull ipsPadding ipsSpacer_bottom">
    <h2>
        <a class="ipsType_brandedLink" href="{$operation->url()}">{$operation->name}</a>
    </h2>
    <p>
        <span>{lang="operation_started"}: </span>
        {$d = \IPS\DateTime::ts($operation->start)->localeDate()}
    </p>
    {{if $operation->end !== null}}
    <p>
        <span>{lang="operation_ended"}: </span>
        {$d = \IPS\DateTime::ts($operation->end)->localeDate()}
    </p>
    {{endif}}
    {$operation->content|raw}
</div>

