<ips:template parameters="$combatUnitForm, $soldierForm" />
<div class="ipsPageHeader ipsBox ipsResponsive_pull ipsPadding ipsSpacer_bottom ipsClearfix">
    <header>
        <h1 class="ipsType_pageTitle">{lang="attendance_sheet_title"}</h1>
        <div class="ipsType_richText ipsType_normal">{lang="attendance_sheet_subtitle"}</div>
    </header>
</div>
<div class="ipsBox ipsResponsive_pull ipsPadding">
    {$combatUnitForm|raw}
    {$soldierForm|raw}
</div>
