<ips:template parameters="$personnel, $combatUnit, $missions, $statistics" />
<div class="ipsPageHeader ipsBox ipsResponsive_pull ipsPadding ipsSpacer_bottom ipsClearfix">
    <header>
        <h1 class="ipsType_pageTitle">{$combatUnit->_title}</h1>
        {{if $statistics['total']['total'] == 0}}
            <p>{lang="attendance_empty"}</p>
        {{else}}
        <ol class="ipsDataList ipsDataList_reducedSpacing">
            {{foreach \IPS\penh\Operation\AfterActionReport::availableStatus() as $status}}
            <li class="ipsDataItem">
                <strong>{$s = ucfirst($status)}: </strong>
                {$c = number_format($statistics['total'][$status] / $statistics['total']['total'], 2) * 100} %
            </li>
            {{endforeach}}
        </ol>
        {{endif}}
    </header>
</div>
{{if $statistics['total']['total'] != 0}}
<div class="ipsBox ipsResponsive_pull ipsSpacer_bottom ipsClearfix tableWrapper">
    <table class="ipsTable ipsTable_zebra">
        <thead>
        <tr>
            <th>{lang="attendance_mission"}</th>
            {{foreach $personnel as $soldier}}
            <th>{$soldier->_title}</th>
            {{endforeach}}
        </tr>
        </thead>
        <tbody>
        {{foreach $missions as $mission}}
        <tr>
            <td>
                <a href="{$mission['mission']->url()}">{$mission['mission']->start()->localeDate()}: {$mission['mission']->name}</a>
            </td>
            {{foreach $personnel as $soldier}}
            <td>
                {{foreach $mission['attendance'] as $attendance}}
                {{if $attendance['soldier']->id == $soldier->id}}
                <span class="attendance-status-{$attendance['attendance']->status}">
                    {$s = ucfirst($attendance['attendance']->status)}
                </span>
                {{endif}}
                {{endforeach}}
            </td>
            {{endforeach}}
        </tr>
        {{endforeach}}
        <tr class="ipsBorder_top"></tr>
        {{foreach \IPS\penh\Operation\AfterActionReport::availableStatus() as $status}}
        <tr>
            <td><strong>{$s = ucfirst($status)}</strong></td>
            {{foreach $personnel as $soldier}}
            <td>
                {$statistics[$soldier->id][$status]} ({$statistics[$soldier->id]['total'] == 0 ? 0 : number_format($statistics[$soldier->id][$status] / $statistics[$soldier->id]['total'], 2) * 100} %)
            </td>
            {{endforeach}}
        </tr>
        {{endforeach}}
        </tbody>
    </table>
</div>
{{endif}}
