<ips:template parameters="$attendance" />
{{if \count($attendance) > 0}}
{{$rowCount = max(array_map(function ($soldiers) { return \count($soldiers); }, $attendance));}}
{{for $i = 0; $i < $rowCount; $i++}}
<tr>
    {{foreach \IPS\penh\Operation\AfterActionReport::availableStatus() as $status}}
    {{$soldier = $attendance[$status][$i] ?? null;}}
    <td>
        {{if $soldier !== null}}
        <div class="ipsType_center">
            {template="soldierRow" group="global" params="$soldier"}
        </div>
        {{endif}}
    </td>
    {{endforeach}}
</tr>
{{endfor}}
{{endif}}
