<ips:template parameters="$soldier" />
{{if $soldier->rank->media == \IPS\perscom\Ranks\Rank::RANK_ICON}}
<i class='rank {$soldier->rank->icon}' title="{$soldier->rank->_title}" data-ipsTooltip></i>
{{else}}
<img src="{file='$soldier->rank->image_small' extension='perscom_Ranks'}" title="{$soldier->rank->_title}" data-ipsTooltip style="height: 15px;"/>
{{endif}}
<a href="{$soldier->url()->__toString()}">{$soldier->_title}</a>
